django_crud_app/django_crud_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls', namespace='user')),
]

django_crud_app/myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'user'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('create/',views.createfunc,name='create'),
    path('login/',views.loginfunc,name='login'),
    path('userhome/',views.userhome,name='userhome'),
    path('deleteuser/<int:user_id>',views.deletefunc,name='deleteuser'),
    path('edituser/<int:user_id>',views.editfunc,name='edituser'),
    path('viewuser/<int:user_id>',views.viewfunc,name='viewuser'),
    path('viewuser/getajax/',views.getajax,name='getajax'),
    path('logoutuser/',views.logoutfunc,name='logoutuser'),

]

django_crud_app/myapp/models.py
from django.db import models

#Create your models here.
class LoginDB(models.Model):
    username=models.CharField(max_length=50,unique=True)
    password=models.CharField(max_length=50)
class UserDB(models.Model):
    name=models.CharField(max_length=50)
    email=models.CharField(max_length=50)
    dob=models.DateField()
    phone=models.IntegerField()
    gender=models.CharField(max_length=10,blank=False)
    city=models.CharField(max_length=100)
    qualification=models.CharField(max_length=10)
    FK_LoginDB=models.ForeignKey(LoginDB,on_delete=models.CASCADE)
    class Meta:
        db_table='usertable'

django_crud_app/myapp/forms.py
from django import forms
from phone_field import PhoneField
from .models import LoginDB,UserDB
from django.forms import ModelForm
GENDER = [('1', 'Male'), ('2', 'Female')]
QUAL_TYPE= [('sslc','SSLC'),('plustwo','PLUSTWO'),('degree','DEGREE'),('pg','PG')]
DOY = ('1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015')
class LoginForm(forms.Form):
    username=forms.CharField(max_length=50,required=True,
    widget=forms.TextInput(attrs={'class':'form-control','placeholder':'username'}))
    password=forms.CharField(max_length=50,required=True,
    widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'password'}))
class RegForm(forms.Form):

#to design model form we use this syntax $ModelForm
#    ''' widgets = {1111
#             'name': forms.TextInput(attrs={
#                 'class': 'form-control',
#                 'name':'name',
#                 'placeholder': 'Enter Name',
#                 'required':True,
#             }),
#             'email':forms.EmailInput(attrs={
#                 'class':'form-control',
#                 'placeholder':'Enter emailid',
#                 'required':True,
#             }),
#     }'''
    usernamereg=forms.CharField(max_length=50,required=True,
    widget=forms.TextInput(attrs={'class':'form-control','placeholder':'enter username'}))
    passwordreg=forms.CharField(min_length=8,required=True,
    widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'enter password'}))
    cpasswordreg=forms.CharField(min_length=8,required=True,
    widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'enter password again'}))
    name = forms.CharField(max_length = 100,required = True,
    widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder':'enter name',
            'pattern' : "[A-Za-z]+"
            }))
    email = forms.CharField(required= True,
    widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
            'placeholder':'enter email'
            }))
    phone = PhoneField(blank=True, help_text='Contact phone number')
    Mobile_Number=forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'mobile number',
                'minlength':"10",
                'maxlength':"10"
            }))
    Gender=forms.CharField(widget=forms.RadioSelect(attrs={'required':True},
                choices=GENDER
            ))

    city=forms.CharField(max_length=100,
    widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder':'enter city',
            'required':True,
            'pattern':"[a-zA-Z]+"

    }))
    qualification=forms.ChoiceField(
        widget=forms.Select(
            attrs={'class':'form-control'}),
            choices=QUAL_TYPE)
    dob=forms.DateField(widget=forms.SelectDateWidget(attrs={'class':''},years=DOY))

django_crud_app/myapp/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.core.exceptions import ObjectDoesNotExist
from django.db import connection,IntegrityError
from django.contrib import messages
from .forms import RegForm,LoginForm
from .models import UserDB,LoginDB
import json
# from util.db import to_dict
# Create your views here.
def home(request):
    obj=UserDB.objects.all()
    return render(request,'reg.html',{'obj':obj})
def loginfunc(request):
    if request.method=='POST':
        forms=LoginForm(request.POST)
        if forms.is_valid():
            uname=forms.cleaned_data['username']
            passw=forms.cleaned_data['password']
            try:
                obj=LoginDB.objects.get(username=uname,password=passw)
                request.session['id']=obj.id
                return redirect('user:userhome')
            except ObjectDoesNotExist:
                messages.add_message(
                request,
                messages.ERROR,
                'userrname or password incorrect'
                )
                return redirect('user:login')
    else:
        forms=LoginForm() 
        return render(request,'create.html',{'f':'login','form':forms})
def userhome(request):
    obj=UserDB.objects.all()
    return render(request,'home.html',{'obj':obj,'userid':request.session['id']})
def createfunc(request):
    
    if request.method=="POST":
        forms=RegForm(request.POST)
        if forms.is_valid():
            uname=forms.cleaned_data['usernamereg']
            passw=forms.cleaned_data['passwordreg']
            cpassw=forms.cleaned_data['cpasswordreg']
            if passw != cpassw:
                messages.add_message(
                request,
                messages.ERROR,
                'password not match'
                )
                return redirect('user:create')
            name=forms.cleaned_data['name']
            email=forms.cleaned_data['email']
            mob=forms.cleaned_data['Mobile_Number']
            dob=forms.cleaned_data['dob']
            gender=forms.cleaned_data['Gender']
            city=forms.cleaned_data['city']
            qualifi=forms.cleaned_data['qualification']
            # return render(request,'create.html',{'form':forms})
            try:
                obj=LoginDB(username=uname,password=passw)
                obj.save()
                obj2=UserDB(name=name,email=email,dob=dob,phone=mob,gender=gender,city=city,qualification=qualifi,FK_LoginDB=obj)
                obj2.save()
                messages.add_message(
                request,
                messages.SUCCESS,
                'Student added successfully'
                
            )
                return redirect('user:home')
            except IntegrityError as e:
                messages.add_message(
                request,
                messages.ERROR,
                'username alraedy exists'
            )
            return redirect('user:create')
        else:
             for error_field in forms.errors:
                if error_field in forms.fields:
                    forms.fields[error_field].widget.attrs['class'] += ' is-invalid'
            # return HttpResponse(forms.errors)
    else:
        forms=RegForm()
    return render(request,'create.html',{'form':forms})
def logoutfunc(request):
    del request.session['id']
    return redirect('user:home')
def deletefunc(request,user_id):
    obj=LoginDB.objects.get(id=request.session['id'])
    # obj=UserDB.objects.get(id=user_id)
    obj.delete()
    
    messages.add_message(
                request,
                messages.SUCCESS,
                'Student deleted successfully'
            )
    return (logoutfunc(request))
def editfunc(request,user_id):
    obj=UserDB.objects.get(id=user_id)
    if request.method=='POST':
        name=request.POST['name']
        phone=request.POST['phone']
        city=request.POST['city']
        obj=UserDB.objects.filter(id=user_id).update(name=name,phone=phone,city=city)
        messages.add_message(
                request,
                messages.SUCCESS,
                'Student updated successfully'
            )
        return userhome(request)
    return render(request,'update.html',{'obj':obj,'userid':user_id})
    # form = RegForm(request.POST or None,instance=obj)
    # return render(request,'create.html',{'form':form})
def viewfunc(request,user_id):
    # Executing raw sql queries
    # objlog=UserDB.objects.get(id=user_id)
    # cursor=connection.cursor()
    # cursor.execute("select name,email,gender,city,phone,qualification,dob from usertable where id=%s",[user_id])
    # rs=cursor.fetchone()
    # li=['name','email','gender','city','phone','qualification','dob']
    # zipobj=zip(li,rs)
    # obj=dict(zipobj)
    # if objlog.FK_LoginDB.id==request.session['id']:
    #     obj['username']=objlog.FK_LoginDB.username
    #     obj['password']=objlog.FK_LoginDB.password
    # else:
    #     obj['username']='it is not visible'
    #     obj['password']='it is not visible'
    #converting to dict
    # obj=to_dict(cursor,rs)

    return render(request,'view.html',{'userid':user_id})
def getajax(request):
    data=request.GET.get('user_id')
    objlog=UserDB.objects.get(id=data)
    cursor=connection.cursor()
    cursor.execute("select name,email,gender,city,phone,qualification from usertable where id=%s",[data])
    rs=cursor.fetchone()
    li=['name','email','gender','city','phone','qualification',]
    zipobj=zip(li,(rs))
    obj=dict(zipobj)
    if objlog.FK_LoginDB.id==request.session['id']:
        obj['username']=objlog.FK_LoginDB.username
        obj['password']=objlog.FK_LoginDB.password
    else:
        obj['username']='it is not visible'
        obj['password']='it is not visible'
    name='ok'
    obj=json.dumps(obj)
    return HttpResponse(obj)

django_crud_app/myapp/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>


    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <style>
    h3{
  font-family: Calibri; 
  font-size: 25pt;         
  font-style: normal; 
  font-weight: bold; 
  color:SlateBlue;
  text-align: center; 
  text-decoration: underline
}

table{
  font-family: Calibri; 
  color:white; 
  font-size: 11pt; 
  font-style: normal;
  font-weight: bold;
  text-align:; 
  background-color: rgb(20, 10, 87); 
  border-collapse: collapse; 
  border: 2px solid rgb(19, 19, 20)
}
table.inner{
  border: 0px
}
    
    </style>







    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
     
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}
              
                <table align="center" cellpadding = "15" width="600">
                {% if "login" in f %}
                <h3>Login Here</h3>
                <form action="{% url 'user:login' %}" method="POST">
                    {% csrf_token %}
                 <!--------------------username--------------------------------------------->
                 <tr>
                    <td>USERNAME</td>
                    <td>{{form.username}}
                        {% if form.username.errors %}
                        <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                        </div>
                        {% endif %}
                    </td>
                    </tr>
                <!------------------------password---------------------------------------------->
                <tr>
                    <td>PASSWORD</td>
                    <td>{{form.password}}
                        {% if form.password.errors %}
                        <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                        </div>
                        {% endif %}
                    </td>
                    </tr>
                {% else %}
                <h3>Create Here</h3>
                <form action="{% url 'user:create' %}" method="POST">
                    {% csrf_token %}
                     <!--------------------username--------------------------------------------->
                 <tr>
                    <td>USERNAME</td>
                    <td>{{form.usernamereg}}
                        {% if form.usernamereg.errors %}
                        <div class="invalid-feedback">
                        {% for error in form.usernamereg.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                        </div>
                        {% endif %}
                    </td>
                    </tr>
                <!------------------------password---------------------------------------------->
                <tr>
                    <td>PASSWORD</td>
                    <td>{{form.passwordreg}}
                        {% if form.passwordreg.errors %}
                        <div class="invalid-feedback">
                        {% for error in form.passwordreg.errors %}
                            <p>{{error}}</p>
                        {% endfor %}
                        </div>
                        {% endif %}
                    </td>
                    </tr>
                <!------------------------confirm password---------------------------------------------->
                    <tr>
                        <td>CONFIRM PASSWORD</td>
                        <td>{{form.cpasswordreg}}
                        </td>
                    </tr>
                <!----- First Name ---------------------------------------------------------->
                <tr>
                <td>NAME</td>
                <td>{{form.name}}
                    (A-Z OR a-z(letters) requested)
                    {% if form.name.errors %}
                    <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                        <p>{{error}}</p>
                    {% endfor %}
                    </div>
                    {% endif %}
                </td>
                </tr>
                 
                <!----- Date Of Birth -------------------------------------------------------->
                <tr>
                <td>DATE OF BIRTH</td>
                 
                <td>
                {{form.dob}}</td>
                </tr>
                 
                <!----- Email Id ---------------------------------------------------------->
                <tr>
                <td>EMAIL ID</td>
                <td>{{form.email}}</td>
                {% if form.email.errors %}
                <div class="invalid-feedback">
                {% for error in form.email.errors %}
                    <p>{{error}}</p>
                {% endfor %}
                </div>
                {% endif %}
                </tr>
                 
                <!----- Mobile Number ---------------------------------------------------------->
                <tr>
                <td>MOBILE NUMBER</td>
                <td>
                {{form.Mobile_Number}}
                <!-- {{form.phone}} -->
                (10 digit number)
                {% if form.Mobile_Number.errors %}
                <div class="invalid-feedback">
                {% for error in form.Mobile_Number.errors %}
                    <p>{{error}}</p>
                {% endfor %}
                </div>
            {% endif %}
                </td>
                </tr>
                 
                <!----- Gender ----------------------------------------------------------->
                <tr>
                <td>GENDER</td>
                <td>
                {{form.Gender}}
                </td>
                </tr>
                 
                <!----- City ---------------------------------------------------------->
                <tr>
                <td>CITY</td>
                <td>{{form.city}}
                    (a-z or A-Z letters requested)
                </td>
                </tr>
            
                <!----- Course ---------------------------------------------------------->
                <tr> 
                        <td>Higher Qualification:</td>
                    <td>
                            {{form.qualification}}
                </td>
                </tr>
                {% endif %}
                <!----- Submit and Reset ------------------------------------------------->
                <tr>
                  <td><button><a href="{% url 'user:home' %}">goback</a> </button></td>
                <td colspan="2" align="center">
                <input class="btn btn-success"type="submit" value="Submit">
                <input class="btn btn-danger"type="reset" value="Reset">
                </td>
                </tr>
                </table>
                 
                </form>
</body>
</html>

django_crud_app/myapp/templates/home.html
 <!DOCTYPE html>
<html lang="en">
<head>


    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <style>
                table {
                  font-family: arial, sans-serif;
                  border-collapse: collapse;
                  width: 100%;
                }
                
                 th {
                  background-color: blueviolet;
                  border: 1px solid #6d2f2f;
                  text-align: left;
                  padding: 8px;
                }
                td{
                  border: 1px solid #6d2f2f;
                  text-align: left;
                  padding: 8px;
                }
                
                tr:nth-child(even) {
                  background-color: #6ef5d8;
                }
        </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
  <br>
  {% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
    
        
        <br>
        <table class="container">
          <tr>
            <td><button type="button" style="float: right;" class="btn btn-info"><a style="color:aliceblue;" href="{% url 'user:logoutuser' %}">logout</a></button>
            </th> </tr>
        <tr>
            <th>Name</th>
            <th>Email_ID</th>
            <th>Action</th>
        </tr>
        {% for i in obj %}
        <tr>
          {% csrf_token%}
            <td>{{i.name}}</td>
            <td>{{i.email}}</td>
            
            <td> <button id="myBtnedit"class="btn btn-success"><a style="color:white" href="{% url 'user:viewuser' i.id %}">View</a></button>
              {% if i.FK_LoginDB.id == userid %}
              <button id="myBtnedit"class="btn btn-primary"><a style="color:white" href="{% url 'user:edituser' i.id %}">Edit</a></button>
              <button id="myBtn"class="btn btn-danger student-delete"><a style="color:white" href="{% url 'user:deleteuser' i.id %}">delete</a></button>
              {% endif%}
            </td>
            {% endfor %}
        </tr>
        </table>

        <script>
            $('.student-delete').click(function(e){
                if (!confirm('Are you sure about deleting this student?')) {
                    e.preventDefault()
                }
            })
        </script>
</body>
</html>

django_crud_app/myapp/templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
       <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}


        <div style="margin:50px 50px 50px 50px;">
        <button class="btn btn-success"style="font-color:aliceblue;margin-left: auto;margin-right: 
        auto;display: block"><a style="color:aliceblue;"href= "{% url 'user:create' %}">USER REGISTRATION</a></button>
        </div>
        <div>
        <button  class="btn btn-primary" style="margin-left: auto;margin-right: 
        auto;display: block"><a style="color:aliceblue;"href= "{% url 'user:login' %}">USER LOGIN</a></button>
        </div>
</body>
</html>

django_crud_app/myapp/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
       <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action='' method="POST">

        <form action="{% url 'user:edituser' userid %}" method="POST">
            {% csrf_token %}
            <br>
            <input class="form-control" name='name' type="text" value="{{obj.name}}"><br>
            <input class="form-control"type="text" maxlength="10" name='phone' value={{obj.phone}}><br>
            <input class="form-control"type="text" name='city' value="{{obj.city}}"><br>
            <input type="submit" >

        </form>
    </form>
</body>
</html>

django_crud_app/myapp/templates/view.html
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
* {
  box-sizing: border-box;
}

/* Create two equal columns that floats next to each other */
.column {
  float: left;
  width: 50%;
  padding: 10px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}
/* Style the buttons */
.btn {
  border: none;
  outline: none;
  padding: 12px 16px;
  background-color: #f1f1f1;
  cursor: pointer;
}

.btn:hover {
  background-color: #ddd;
}

.btn.active {
  background-color: #666;
  color: white;
}
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    $("#btndisplay").click(function(){

    $.ajax({
        url: "getajax", 
        data:{user_id:"{{userid}}"},
        success: function(name){
            console.log(typeof(name))
        if(name){
          
            // for (i=0;i<name.length;i++){
            // $("#li"+i).html(name[i]);
            var obj=JSON.parse(name);
            var gender='';
            console.log((obj));
            $("#username").html(obj.username);
            $("#password").html(obj.password);
            $("#phone").html(obj.phone);
            $("#name").html(obj.name);
            $("#email").html(obj.email);
            $("#city").html(obj.city);
            $("#qualification").html(obj.qualification);
            if(obj.gender=='1'){
              gender='male';
            }
            else if(obj.gender=='2'){
              gender='female'
            }
            $("#gender").html(gender);
            // document.getElementByClassName("gender").innerHTML =obj.gender;
            // $("#mylist").append("<li>"+obj.email+"</li>")
            // $("#mylist").append("<li>"+name.passwod+"</li>")
        
            
            // }
        }
        }  
    });
    $("#btndisplay").hide();
    $("#dis").show();
    });
});
</script>
</head>
<body>
  <button id="btndisplay" class="btn btn-primary">click here</button>
<div id ="dis"class="container" style="display:none;">
<div id="btnContainer">
    <button class="btn"><a href="{% url 'user:userhome' %}">go back</a></button>
  <button class="btn" onclick="listView()"><i class="fa fa-bars"></i> List</button> 
  <button class="btn active" onclick="gridView()"><i class="fa fa-th-large"></i> Grid</button>
</div>
<br>
<div class="row">
    <div class="column" style="background-color:rgb(199, 243, 186);">
      <h2>Username</h2>
      <p class="abc" id="username">{{obj.username}}</p>
    </div>
    <div class="column" style="background-color:rgb(156, 192, 145);">
      <h2>Password</h2>
      <p id="password">{{obj.password}}</p>
    </div>
</div>


<div class="row">
  <div class="column" style="background-color:#aaa;">
    <h2>Name:</h2>
    <p id="name">{{obj.name}}</p>
  </div>
  <div class="column" style="background-color:#bbb;">
    <h2>Email:</h2>
    <p id="email">{{obj.email}}</p>
  </div>
</div>

<div class="row">
    <div class="column" style="background-color:rgb(241, 204, 204);">
      <h2>Gender:</h2>
      <p id="gender"></p>
    </div>
    <div class="column" style="background-color:rgb(238, 192, 192);">
      <h2>City:</h2>
      <p id="city">{{obj.city}}</p>
    </div>
</div>

<div class="row">
  <div class="column" style="background-color:#ccc;">
    <h2>Phone Number</h2>
    <p id="phone">{{obj.phone}}</p>
  </div>
  <div class="column" style="background-color:rgb(146, 122, 122)";>
    <h2>Qualification:</h2>
    <p id="qualification">{{obj.qualification}}</p>
  </div>
</div>
<script>
// Get the elements with class="column"
var elements = document.getElementsByClassName("column");

// Declare a loop variable
var i;

// List View
function listView() {
  for (i = 0; i < elements.length; i++) {
    elements[i].style.width = "100%";
  }
}

// Grid View
function gridView() {
  for (i = 0; i < elements.length; i++) {
    elements[i].style.width = "50%";
  }
}

/* Optional: Add active class to the current button (highlight it) */
var container = document.getElementById("btnContainer");
var btns = container.getElementsByClassName("btn");
for (var i = 0; i < btns.length; i++) {
  btns[i].addEventListener("click", function() {
    var current = document.getElementsByClassName("active");
    current[0].className = current[0].className.replace(" active", "");
    this.className += " active";
  });
}
</script>

</body>
</html>