auth_sample/authsample/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',include('myapp.urls'))
]

auth_sample/myapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='myapp'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homefunc,name='home'),
    path('reguser/',views.myfunc,name='reguser'),
    path('edituser/<int:userid>',views.editfun,name='edituser'),
    path('logoutuser/',views.logoutfunc,name='logoutuser')
]

auth_sample/myapp/models.py
from django.db import models

# Create your models here.
class MyDB(models.Model):
    username=models.CharField(max_length=50)
    email=models.EmailField(max_length=50)
    passw=models.CharField(max_length=50)

auth_sample/myapp/forms.py
from django import forms
from .models import MyDB
from django.forms import ModelForm

class LoginForm(forms.Form):
    usern=forms.CharField(max_length=50)
    passw=forms.CharField(max_length=50)

class MyForm(ModelForm,forms.Form):
    confirmpassw=forms.CharField(max_length=50,widget=forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'confirm password'
        }))
    class Meta:

        model=MyDB

        fields=['username','email','passw']

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter username',
                'required':True
            }),

            'email':forms.TextInput(attrs={

                'class':'form-control',
                'placeholder':'enter email',
                'type':'email',
                'required':True
            }),
            'passw':forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'enter password'
            })
        }
        

auth_sample/myapp/views.py
from django.shortcuts import render,HttpResponse,redirect
from .forms import MyForm,LoginForm
from .models import MyDB
# Create your views here.
def homefunc(request):
    if request.method=='POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            form.clean()
            usern=form.cleaned_data['usern']
            passw=form.cleaned_data['passw']
            obj=MyDB.objects.all()
            for i in obj:
                if i.username==usern and i.passw==passw:
                    request.session['id']=i.id
                    return render(request,'home.html',{'userid':request.session['id']})
            return HttpResponse('cannot login')
    else:
        form=LoginForm()
    return render(request,'login.html',{'form':form})

def myfunc(request):
    if request.method=='POST':
        form=MyForm(request.POST)
        if form.is_valid():
            form.clean()
            usern=form.cleaned_data['username']
            email=form.cleaned_data['email']
            passw=form.cleaned_data['passw']
            cpassw=form.cleaned_data['confirmpassw']
            if passw !=cpassw:
                return HttpResponse('password not match')
            else:
                form.save()
                obj=MyDB.objects.latest('id')
                request.session['id']=obj.id
                return render(request,'home.html',{'userid':request.session['id']})
    else:
        form=MyForm()
    return render(request,'view.html',{'form':form})
def editfun(request,userid):
    obj=MyDB.objects.get(id=userid)
    form=MyForm(request.POST or None,instance=obj)
    if request.method=='POST':
        if form.is_valid():
            form.save()
            # Setting success flash message
            messages.add_message(
                request,
                messages.SUCCESS,
                'Student data updated successfully'
            )
            # Redirecting user back to student listing
            return render(request,'home.html',{'userid':request.session['id']})
    return render(request,'view.html',{'form':form})
def logoutfunc(request):
    del request.session['id']
    return redirect('myapp:home')

auth_sample/myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        
        <!-- Popper JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        
        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    {% endblock %}
    
</body>
</html>

auth_sample/myapp/templates/home.html
{% extends 'base.html' %}
{% block content%}
<h1>home</h1>
<button><a href="{% url 'myapp:logoutuser'%}">logout</a></button>
<button><a href="{% url 'myapp:edituser' userid %}">edit</a></button>
{% endblock %}

auth_sample/myapp/templates/login.html
{% extends 'base.html' %}
{% block content%}
<h1>welcome</h1>
<form action="{% url 'myapp:home' %}" method="POST">
    {% csrf_token %}
    username:{{form.usern}}<br>
    password:{{form.passw}}<br>
<input type="submit">
</form>
<button><a href="{% url 'myapp:reguser'%}">register</a></button>
{% endblock %}

auth_sample/myapp/templates/view.html
{% extends "base.html" %}
{% block content%}
<form action='{% url 'myapp:reguser' %}' method="POST">
    {% csrf_token %}
        {{form.username}}
        {{form.email}}
        {{form.passw}}
        {{form.confirmpassw}}
        <br>
        <input type="submit" class="btn btn-info">
    </form>
{% endblock %}